# Generated by Django 4.2.5 on 2023-11-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isBorrow',
            field=models.BooleanField(default=False, verbose_name='外借中'),
        ),
        migrations.AddField(
            model_name='post',
            name='write',
            field=models.CharField(default='不詳', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1),
        ),
    ]
