# Generated by Django 4.2.5 on 2023-11-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_post_isborrow_post_write_alter_post_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('一般書籍', '一般書籍'), ('教學用書', '教學用書')], default='一般書籍', max_length=20),
        ),
    ]
