# Generated by Django 4.2.5 on 2023-11-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='intro',
            field=models.TextField(default='', null=True),
        ),
    ]
