# Generated by Django 4.2.4 on 2024-01-03 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_alter_book_id_alter_borrowinghistory_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowinghistory',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.book'),
        ),
        migrations.CreateModel(
            name='BorrowingHistor2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('br', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.post')),
            ],
        ),
    ]
