# Generated by Django 4.2.4 on 2024-01-03 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_alter_borrowinghistory_book_borrowinghistor2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowinghistory',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.post'),
        ),
    ]
