# Generated by Django 4.2.6 on 2024-01-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_alter_borrowinghistory_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowinghistor2',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
