# Generated by Django 4.2.6 on 2024-01-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_alter_borrowinghistor2_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowinghistor2',
            name='br',
            field=models.CharField(choices=[('B', '借'), ('R', '還')], max_length=1),
        ),
    ]
