# Generated by Django 4.2.4 on 2024-01-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0003_alter_post_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='nickname',
            field=models.CharField(default='不願意透漏身份的人', max_length=10),
        ),
    ]
